import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Hero from '../components/Hero'
import UniqueArt from "~/components/UniqueArt";
import Subscribe from "~/components/Subscribe";
import Footer from "~/components/Footer";
import WeeklyArtists from "~/components/WeeklyArtitsts";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main" suppressHydrationWarning>
        <div suppressHydrationWarning  className="mx-auto max-w-[1400px] overflow-x-hidden px-2 md:px-4">
        <NavBar />
          <Hero />
          <UniqueArt />
          <WeeklyArtists />
          <Subscribe />
          <Footer />
        </div>
      </div>
    </>
  );
};

export default Home;
