import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-4 md:px-8 bg-blue-900">
        <NavBar></NavBar>
      </div>
    </>
  );
};

export default Home;
