import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Hero from '../components/Hero'
import UniqueArt from "~/components/UniqueArt";
import Subscribe from "~/components/Subscribe";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-900">
        <div className="mx-auto max-w-[1200px] px-4 md:px-8 ">
          <NavBar></NavBar>
          <Hero />
          <UniqueArt />
          <Subscribe />
        </div>
      </div>
    </>
  );
};

export default Home;
